//All GSAP easings, original is needed because every animation comes with the "curated/selected" easing for its purpose, original is "the best fit"

export const easings = [
  "original",
  "power1",
  "power1.in",
  "power1.inOut",
  "power1.out",
  "power2",
  "power2.in",
  "power2.inOut",
  "power2.out",
  "power3",
  "power3.in",
  "power3.inOut",
  "power3.out",
  "power4",
  "power4.in",
  "power4.inOut",
  "power4.out",
  "back",
  "back.in",
  "back.inOut",
  "back.out",
  "bounce",
  "bounce.in",
  "bounce.inOut",
  "bounce.out",
  "circ",
  "circ.in",
  "circ.inOut",
  "circ.out",
  "elastic",
  "elastic.in",
  "elastic.inOut",
  "elastic.out",
  "expo",
  "expo.in",
  "expo.inOut",
  "expo.out",
  "sine",
  "sine.in",
  "sine.inOut",
  "sine.out",
  "none",
] as const;

export type Easing = (typeof easings)[number];
